version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db

  phpfpm:
    image: itkdev/php7.2-fpm:latest
    networks:
      - app
    environment:
      - PHP_XDEBUG=${PHP_XDEBUG:-0}
      - PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART:-0}
      - PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST:-0.0.0.0}
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAIL=1
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - PHP_IDE_CONFIG=serverName=localhost
    depends_on:
      - mariadb
    volumes:
      - ./:/app:cached

  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
      - search-node
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/app/web:cached,ro
      - ./vendor:/app/vendor:cached,ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  memcached:
    image: 'memcached:latest'
    networks:
      - app
    ports:
      - '11211'
    environment:
      - MEMCACHED_CACHE_SIZE=64

  mailhog:
    image: mailhog/mailhog
    networks:
      - app
    ports:
      - "1025"
      - "8025"

  redis:
    image: 'redis:4'
    networks:
      - app
    ports:
      - '6379'

  middleware:
    build: .docker/middleware/
    command: node app.js
    networks:
      - app
    ports:
      - 8002:3020

  search-node:
    build: .docker/search/
    command: node app.js
    depends_on:
      - elasticsearch
    networks:
      - app
    ports:
      - 8001:3010

  elasticsearch:
    build: .docker/elasticsearch/
    networks:
      - app
    ports:
      - 9200:9200
