imports:
- { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: '%debug_toolbar%'
    intercept_redirects: '%debug_redirects%'

monolog:
    channels: ['zencoder']
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  warning
        zencoder:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.zencoder.log"
            level:  debug
            channels: [zencoder]
        deprecation:
            type: "null"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        console:
            type:   console
            bubble: false
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911

swiftmailer:
    transport: smtp
    host:      127.0.0.1
    username:  null
    password:  null
    port: 1025
    spool:     { type: memory }

os2_display_screen:
    strategies:
        pull:
            debug: true
            log_to_console: true
            log_level: all
            update_interval: 60
        push:
            debug: true
            log_to_console: true
            log_level: all

# Disable cache in dev.
os2_display_core:
    cache_ttl: 0

# Disable cache in dev.
os2_display_campaign:
    cache_ttl: 0

# Disable cron interval in dev.
os2_display_poster:
    cron_interval: 0

# Disable cron interval in dev.
os2_display_sparkle_feed:
    cron_interval: 0
